platform:ios, '8.0'


target 'RecordVoice' do

pod 'AFNetworking', '3.0.1'

pod 'SDWebImage', '~> 5.0.0-beta5'

end



target 'RecordVoice test' do
  
  pod 'AFNetworking', '3.0.1'
  
  pod 'SDWebImage', '~> 5.0.0-beta5'
  
end
